[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "multi-agent-power-allocation"
version = "0.1.0"
description = "Multi-agent power allocation with DRL"
authors = [
  { name = "Nguyen Duc Tai", email = "ductaingn.015203@gmail.com" }
]
maintainers = [
  { name = "Nguyen Duc Tai", email = "ductaingn.015203@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "numpy==2.2.5",
  "torch==2.6.0",
  "tianshou==0.5.1",
  "gymnasium==1.0.0",
  "pettingzoo==1.25.0",
  "safetensors==0.5.3",
  "tensorboard==2.20.0",
  "tensorboardX==2.6.4",
  "tensorboard-data-server==0.7.2",
  "wandb==0.19.11"
]

[project.scripts]
train_pamarl = "multi_agent_power_allocation.run.train:main"

[tool.setuptools.packages.find]
where = ["src"]